version: '3.8'

services:
  postgres_dev:
    container_name: 'postgres-dev'
    image: 'postgres:14.1-alpine'
    environment:
      POSTGRES_USER: 'local_user'
      POSTGRES_PASSWORD: 'local_password'
      POSTGRES_DB: 'track'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped

  redis_dev:
    container_name: 'redis-dev'
    image: 'redis:6.0-alpine'
    ports:
      - '6379:6379'
    restart: unless-stopped

volumes:
  postgres_data:
